### ISSUE TITLE
Enable deployment from macOS by adding to vars.tf

### ISSUE THREAD

**Issue by liveaverage** [RedHatSI/openshift-packet-deploy#17]
Currently the only supported execution environment is Linux, but we should be able to accommodate macOS (and the relevant `oc` and `openshift-install` binaries) by checking for execution environment via variable. Need to update the bash script for https://github.com/RedHatSI/openshift-packet-deploy/blob/master/terraform/modules/prereq/scripts/get-ocp-installer.sh to check for a `PLATFORM` var

**Comment by c0dyhi11** [comment]
@liveaverage why not move the artifacts download and deployment into the nginx box?
This will make our lives easier and we can control the the install ENV.
Basically just update all local-exec to remote-exec.

If you think this is a good Idea. I can take on this work.

**Comment by liveaverage** [comment]
@wtcross and I debated this, too. For testing it made sense to use local-exec so I didn't add provisioning time (when re-downloading binaries for `oc` and `openshift-install`) each time I tore down and reprovisioned a new cluster. Since I think moving to remote-exec will resolve this issue _and_ allow us to stage bare metal images to speed-up deployment, I think I'll knock this out today.

**Comment by liveaverage** [comment]
Fixed by #38. This should technically work fine on Windows too, but only if we remove the step to copy/scp the generated kubeconfig: https://github.com/RedHatSI/openshift-packet-deploy/blob/master/terraform/output.tf#L6
