### ISSUE TITLE
Optional Components

### ISSUE THREAD

**Issue by c0dyhi11** [RedHatSI/openshift-packet-deploy#32]
Hey @liveaverage:
I think we should be trying to keep OpenShift 100% vanilla and opinionated in things such as NFS.
This can be done with variables such as `enable_nfs = ture` and if it's not enabled then NFS doesn't get installed. This will allow us to make these things modular and if we want to do things like OpenShift Container Storage we can optionally. 

I'd also like to see if we could make NS1 and Route53 options for DNS as well.

**Comment by liveaverage** [comment]
+1 @c0dyhi11 -- i'll split NFS, Let's Encrypt, etc. into modules that can easily be enabled/disabled.
